// Code generated by "stringer -type=ErrorType -output=error_string.go"; DO NOT EDIT.

package sstring

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IntConvertError-0]
}

const _ErrorType_name = "IntConvertError"

var _ErrorType_index = [...]uint8{0, 15}

func (i ErrorType) String() string {
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
