// Code generated by "stringer -type=ErrorType"; DO NOT EDIT.

package simplehttp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidBodyType-0]
	_ = x[CreateRequestError-1]
	_ = x[DoRequestError-2]
	_ = x[ResponseReadBodyError-3]
	_ = x[ResponseUnmarshalError-4]
	_ = x[ResponseWriteError-5]
}

const _ErrorType_name = "InvalidBodyTypeCreateRequestErrorDoRequestErrorResponseReadBodyErrorResponseUnmarshalErrorResponseWriteError"

var _ErrorType_index = [...]uint8{0, 15, 33, 47, 68, 90, 108}

func (i ErrorType) String() string {
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
